// frontend/src/components/casestudy/mepp/MpArchitecture.tsx
import { Database, KeyRound, ScanSearch, EyeOff } from 'lucide-react'
import { CsSection, Module } from '../bits'
import { DBox, HArrow, VArrow, Boundary, DiagramPair } from './svg'

const DIAGRAM_LABEL =
  'Clinician requests reach a tenant-scoped API, which enters a dashed tenant trust boundary containing PostgreSQL with forced row-level security, an encrypted PHI store and a blind index. A separate de-identified projection leaves the boundary and is the only path that reaches vendors.'

function WideDiagram() {
  return (
    <svg viewBox="0 0 920 340" className="h-auto w-full" role="img" aria-label={DIAGRAM_LABEL}>
      <title>MEPP architecture: tenant boundary and de-identified vendor path</title>

      <DBox x={8} y={54} w={140} h={58} label="Clinician" sub="web client" />
      <HArrow x1={148} x2={188} y={83} />
      <DBox x={190} y={54} w={150} h={58} label="API" sub="TypeScript" />
      <HArrow x1={340} x2={394} y={83} />

      <Boundary x={382} y={20} w={350} h={300} label="TENANT BOUNDARY · app.tenant_id" />

      <DBox x={396} y={54} w={320} h={58} label="PostgreSQL · FORCE RLS" sub="policies on a non-BYPASSRLS role" />
      <VArrow x={476} y1={112} y2={140} />
      <VArrow x={636} y1={112} y2={140} />
      <DBox x={396} y={142} w={152} h={64} label="Encrypted PHI" sub="AES-256-GCM" tone="plum" />
      <DBox x={564} y={142} w={152} h={64} label="Blind index" sub="keyed HMAC digest" tone="plum" />
      <VArrow x={476} y1={206} y2={236} />
      <DBox x={396} y={238} w={320} h={58} label="De-identified projection" sub="identity columns never selected" tone="muted" />

      <HArrow x1={716} x2={788} y={267} tone="plum" />
      <DBox x={790} y={236} w={122} h={62} label="Vendor" sub="fulfilment" />
    </svg>
  )
}

function StackedDiagram() {
  return (
    <svg viewBox="0 0 320 520" className="mx-auto h-auto w-full max-w-[360px]" role="img" aria-label={DIAGRAM_LABEL}>
      <title>MEPP architecture: tenant boundary and de-identified vendor path</title>

      <DBox x={20} y={8} w={280} h={50} label="Clinician" sub="web client" fs={12} />
      <VArrow x={160} y1={58} y2={82} />
      <DBox x={20} y={84} w={280} h={50} label="API · TypeScript" fs={12} />
      <VArrow x={160} y1={134} y2={158} />

      <Boundary x={6} y={160} w={308} h={270} label="TENANT BOUNDARY · app.tenant_id" />

      <DBox x={18} y={186} w={284} h={54} label="PostgreSQL · FORCE RLS" sub="non-BYPASSRLS app role" fs={11.5} />
      <VArrow x={87} y1={240} y2={264} />
      <VArrow x={233} y1={240} y2={264} />
      <DBox x={18} y={266} w={138} h={58} label="Encrypted PHI" sub="AES-256-GCM" tone="plum" fs={11} />
      <DBox x={164} y={266} w={138} h={58} label="Blind index" sub="keyed HMAC" tone="plum" fs={11} />
      <VArrow x={160} y1={324} y2={350} />
      <DBox x={18} y={352} w={284} h={54} label="De-identified projection" sub="no identity columns" fs={11.5} tone="muted" />

      <VArrow x={160} y1={430} y2={456} tone="plum" />
      <DBox x={18} y={458} w={284} h={50} label="Vendor · fulfilment" fs={12} />
    </svg>
  )
}

const LAYERS = [
  {
    Icon: Database,
    title: 'RLS lives in SQL',
    body: 'Policies are hand-written in migrations, not generated by the ORM. The database is the last word on tenancy.',
  },
  {
    Icon: KeyRound,
    title: 'FORCE ROW LEVEL SECURITY',
    body: 'Applied on a role without BYPASSRLS, so the application role cannot escape its own policies.',
  },
  {
    Icon: ScanSearch,
    title: 'Encrypt at the application',
    body: 'PHI is sealed with AES-256-GCM in utils/phi-encryption.ts before it reaches a column.',
  },
  {
    Icon: EyeOff,
    title: 'Projection, not filtering',
    body: 'The vendor view is a separate de-identified read path. There is no identity to forget to strip.',
  },
]

export function MpArchitecture() {
  return (
    <CsSection
      id="architecture"
      eyebrow="02 · Architecture"
      title="One boundary, and a second door that identity cannot walk through."
      intro="Everything that can read a patient sits inside a tenant-scoped enclosure. Vendors are served by a separate projection that never selects identity columns."
    >
      <Module>
        <DiagramPair
          wide={<WideDiagram />}
          stacked={<StackedDiagram />}
          caption="Dashed enclosure = the tenant trust boundary enforced by row-level security keyed on app.tenant_id."
        />
      </Module>

      <div className="mt-6 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
        {LAYERS.map(({ Icon, title, body }) => (
          <div key={title} className="rounded-2xl bg-white p-5 ghair soft-shadow-sm">
            <div className="grid h-10 w-10 place-items-center rounded-xl" style={{ background: 'var(--plum-soft)' }}>
              <Icon size={18} style={{ color: 'var(--plum)' }} strokeWidth={1.9} />
            </div>
            <h3 className="mt-3 font-display text-[15px] font-bold text-ink">{title}</h3>
            <p className="mt-1.5 text-[13px] leading-relaxed text-ink-soft">{body}</p>
          </div>
        ))}
      </div>
    </CsSection>
  )
}
